---
decks:
  - cardsParser: csv
    list: ./react/basic-layout-with-image.csv
    layout: react
    outputDir: generated
    output:
      - renderer: raw
        outputDir: raw-layout
      - renderer: nodeIndividual
        outputDir: individual
