name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Run card-gen
        run: yarn card-gen

      - name: Archive generated cards
        uses: actions/upload-artifact@v4
        with:
          name: generated-cards
          path: generated
